### PR TITLE
Always store url for guild icon, splash and banner

### PR DESCRIPTION
**Pull request by Xpl0itR**
Always store url for guild icon, splash and banner

### CODE REVIEW

**Comment by Androz2091** [comment]
If the image is already stored in base64, what is the point of storing the URL? 🤔

**Comment by Xpl0itR** [comment]
Because MessageEmbed's setImage and setThumbnail methods take URLs.

**Comment by Androz2091** [comment]
Oh I see. That's a good idea, so. But we should modify this:
https://github.com/Androz2091/discord-backup/blob/master/src/master/load.ts#L12
to make sure that if a base64 image is provided, the bot restores that one and not the URL. Just reverse the conditions:
```Js
if (backupData.iconURL) {
    guild.setIcon(backupData.iconURL);
} else if (backupData.iconBase64) {
    guild.setIcon(new Buffer(backupData.iconBase64, 'base64'));
}
```
=> 
```Js
if (backupData.iconBase64) {
    guild.setIcon(new Buffer(backupData.iconBase64, 'base64'));
} else if (backupData.iconURL) {
    guild.setIcon(backupData.iconURL);
}
```

**Comment by Xpl0itR** [comment]
Done. Also fixed a bug where it was using the banner to set the icon.

**Pull request merged**
