### PR TITLE
✏ Add support for discord.js v14 

### PR DESCRIPTION
**Pull request by lolollllo**
Adds support for discord.js v14 to discord-backup

### CODE REVIEW

**Comment by lolollllo** [comment]
I'll finish this when I get back from holiday!

**Comment by NathanLFG** [comment]
How can one install with "npm i" this version of the module?

**Comment by SimonLeclere** [comment]
`npm i https://github.com/lolollllo/discord-backup.git` should work

**Comment by AlienFreek** [comment]
`npm i git://github.com/lolollllo/discord-backup.git#discordjs-v14` since this is a branch, however, due to the way the package is set up (it is a clone of /Androz2091/discord-backup, not an independent package) it would be better to download and install it locally until it is officially updated.

**Review by Androz2091 — APPROVED** [review]
Awesome, thank you for your contribution

**Pull request merged**
