### PR TITLE
Djs v13 compatability

### PR DESCRIPTION
**Pull request by tandpfun**

### CODE REVIEW

**Comment by tandpfun** [comment]
PR'd wrong repo, whoops.

**Comment by Androz2091** [comment]
This is still interesting for this repo, right? You can let it open and I will review it 😉

**Comment by tandpfun** [comment]
Yeah, I've made some changes on master of my fork since. Could you make a branch for v13 and I'll pr into it with the latest changes I have.

**Comment by Androz2091** [comment]
@tandpfun, discordjs-v13 branch has been created, feel free to target it ;)

**Pull request closed without merging**
